### ISSUE TITLE
Pushing a function to the pool

### ISSUE THREAD

**Issue by prayritkhanna** [vit-vit/CTPL#24]
Hello, 
Thank you so much for this library. I was wondering why I keep getting an error to push to the pool:
all_errors.cpp:244:25: error: no matching function for call to ‘ctpl::thread_pool::push(int)’

I am following your example to the tee and I am still getting this error. Any ideas?

**Comment by pemsley** [comment]
You need an extra argument in your function

int mytask(int ithread, int i) {
 // do stuff with i
}

**Comment by prayritkhanna** [comment]
Thank you for your timely response @pemsley . I actually wasn't including the lambda function properly to the code.
